
classdef OctomapResponse < ros.Message
    %OctomapResponse MATLAB implementation of rotors_comm/OctomapResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rotors_comm/OctomapResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '57e29816a04b311c573d5337632a1156' % The MD5 Checksum of the message definition
        PropertyList = { 'Map' 'OriginLatitude' 'OriginLongitude' 'OriginAltitude' } % List of non-constant message properties
        ROSPropertyList = { 'map' 'origin_latitude' 'origin_longitude' 'origin_altitude' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.octomap_msgs.Octomap' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Map
        OriginLatitude
        OriginLongitude
        OriginAltitude
    end
    methods
        function set.Map(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.octomap_msgs.Octomap'};
            validateattributes(val, validClasses, validAttributes, 'OctomapResponse', 'Map')
            obj.Map = val;
        end
        function set.OriginLatitude(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OctomapResponse', 'OriginLatitude');
            obj.OriginLatitude = double(val);
        end
        function set.OriginLongitude(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OctomapResponse', 'OriginLongitude');
            obj.OriginLongitude = double(val);
        end
        function set.OriginAltitude(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OctomapResponse', 'OriginAltitude');
            obj.OriginAltitude = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rotors_comm.OctomapResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rotors_comm.OctomapResponse(strObj);
        end
    end
end
