
classdef RecordRosbagRequest < ros.Message
    %RecordRosbagRequest MATLAB implementation of rotors_comm/RecordRosbagRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rotors_comm/RecordRosbagRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '396b06ea5fee4a93fc2d2be6c15809f7' % The MD5 Checksum of the message definition
        PropertyList = { 'Record' } % List of non-constant message properties
        ROSPropertyList = { 'record' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Record
    end
    methods
        function set.Record(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RecordRosbagRequest', 'Record');
            obj.Record = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rotors_comm.RecordRosbagRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rotors_comm.RecordRosbagRequest(strObj);
        end
    end
end
