
classdef WindSpeed < ros.Message
    %WindSpeed MATLAB implementation of rotors_comm/WindSpeed
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'rotors_comm/WindSpeed' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ae00d2a331b8545eaf96c531128ff0ef' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Velocity' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'velocity' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Velocity
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'WindSpeed', 'Header')
            obj.Header = val;
        end
        function set.Velocity(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'WindSpeed', 'Velocity')
            obj.Velocity = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.rotors_comm.WindSpeed.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.rotors_comm.WindSpeed(strObj);
        end
    end
end
