// Generated by gencpp from file rotors_comm/reset_simulationRequest.msg
// DO NOT EDIT!


#ifndef ROTORS_COMM_MESSAGE_RESET_SIMULATIONREQUEST_H
#define ROTORS_COMM_MESSAGE_RESET_SIMULATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rotors_comm
{
template <class ContainerAllocator>
struct reset_simulationRequest_
{
  typedef reset_simulationRequest_<ContainerAllocator> Type;

  reset_simulationRequest_()
    {
    }
  reset_simulationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reset_simulationRequest_

typedef ::rotors_comm::reset_simulationRequest_<std::allocator<void> > reset_simulationRequest;

typedef boost::shared_ptr< ::rotors_comm::reset_simulationRequest > reset_simulationRequestPtr;
typedef boost::shared_ptr< ::rotors_comm::reset_simulationRequest const> reset_simulationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rotors_comm::reset_simulationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rotors_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rotors_comm::reset_simulationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rotors_comm/reset_simulationRequest";
  }

  static const char* value(const ::rotors_comm::reset_simulationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rotors_comm::reset_simulationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_simulationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rotors_comm::reset_simulationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rotors_comm::reset_simulationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROTORS_COMM_MESSAGE_RESET_SIMULATIONREQUEST_H
